services:
  - type: web
    name: job-sheet
    runtime: elixir
    buildCommand: ./build.sh
    startCommand: mix phx.server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        fromService:
          type: web
          name: job-sheet
          property: hostnames[0]
      - key: PHX_SERVER
        value: true
      - key: MIX_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: job-sheet-db
          property: connectionString
      - key: POOL_SIZE
        value: 2

databases:
  - name: job-sheet-db
    plan: free
    postgresMajorVersion: 15
